package RecuP1;
// Generated 20 abr 2024 13:25:01 by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Programas generated by hbm2java
 */
public class Programas implements java.io.Serializable {

	private String codPro;
	private String nombre;
	private String ver;
	private Set fabricanteses = new HashSet(0);

	public Programas() {
	}

	public Programas(String codPro) {
		this.codPro = codPro;
	}

	public Programas(String codPro, String nombre, String ver, Set fabricanteses) {
		this.codPro = codPro;
		this.nombre = nombre;
		this.ver = ver;
		this.fabricanteses = fabricanteses;
	}

	public String getCodPro() {
		return this.codPro;
	}

	public void setCodPro(String codPro) {
		this.codPro = codPro;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getVer() {
		return this.ver;
	}

	public void setVer(String ver) {
		this.ver = ver;
	}

	public Set getFabricanteses() {
		return this.fabricanteses;
	}

	public void setFabricanteses(Set fabricanteses) {
		this.fabricanteses = fabricanteses;
	}

}
